### ISSUE TITLE
Cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by eladent** [J4FSec/In0ri#10]
Hello,

I just tried to deploy the project using docker. I got this error related to Flask.

```
Traceback (most recent call last):
  File "/opt/In0ri/api.py", line 6, in <module>
    from flask import Flask, request
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)
```
Linked to the end of support of soft_unicode by  markupsafe tha removed `soft_unicode' https://github.com/pallets/markupsafe/issues/304 ; and 
https://github.com/pallets/markupsafe/issues/282

Could you please patch the software (or downgrade to markupsafe==2.0.1) ? and rebuild the docker container on docker hub  ?

Thanks in advance

**Comment by cvaughan79** [comment]
Having the same problem with the Docker image. 

Getting Watchdog issues when simply running agent.py on new builds in CentOS and Ubuntu too.

Would love to be able to get this running.

Thanks!

**Comment by watch-dog-man** [comment]
@Qynklee has implemented the fix, please check

**Comment by cse0001** [comment]
The root cause with your issue stems from a dependency management conflict between two software ecosystems. According to the error message, your 'markupsafe' was installed using 'pip' at the path `/usr/local/lib/python3.8/dist-packages/markupsafe/`. The 'jinja2' that depends on it was installed using 'apt' at the path `/usr/lib/python3/dist-packages/jinja2`. The versions of the two are not compatible. In fact, there is a version of 'markupsafe' in the system that 'jinja2' correctly depends on, but the Python interpreter prioritizes the 'markupsafe' installed by 'pip', leading to this issue. There are typically two solutions to this problem: (1) Use 'pip' to uninstall markupsafe, and then reinstall it using 'apt', or uninstall 'jinja2' using 'apt' and reinstall it using 'pip'. (2) Use Python's imp module to customize the path and import the 'markupsafe' from the 'apt' path before importing 'jinja2'. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('markupsafe', path)
    imp.load_module("markupsafe", fp, pathname, description)

Hope my diagnosis is helpful to you！ @eladent
